#!/bin/bash

# path to the root of the dumps tree, under which the
# directories public, private and temp must exist
BASEROOT="/home/ariel/dumptesting/dumpruns"

# date of old versions of the xml/sql dumps which should
# be known good dumps; the content from these will be
# used for comparison against dumps output generated
# by these tests
# you will want the following subdirectories under public:
# <wikiname>/$DATE.prefix
# with data generated by a run where prefetches are used, 
# <wikiname>/$DATE.revinfo
# with data generated by a run wit revinfostash enabled
# and the following directories under private:
# <wikiname>/$DATE.prefix
# with data generated by a run where prefetches are used
DATE=20200214

